# Generated by Django 5.0.3 on 2024-03-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_nome', models.CharField(default='', max_length=60)),
                ('filme_diretor', models.CharField(default='', max_length=60)),
                ('filme_duracao', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_num', models.IntegerField(primary_key=True, serialize=False)),
                ('sala_descricao', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalaFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema_root.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cinema_root.sala')),
            ],
        ),
    ]
